# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn_rl',
                'doc_host': 'https://pankaj-kvhld.github.io',
                'git_url': 'https://github.com/pankaj-kvhld/learn_rl',
                'lib_path': 'learn_rl'},
  'syms': {'learn_rl.core': {'learn_rl.core.foo': ('core.html#foo', 'learn_rl/core.py')}}}
